---

- name: For Debian
  block: -----Debian------
    - name: Install nginx to Deb

      apt:

         pkg: nginx

      become: yes

    - name: Create dir for websites

      file:

         path: /var/www/{{ item }}

         state: directory

      become: yes

      with_items: "{{ siteslist }}"

    - name: Create nginx config files

      template:

         src: "testsite.j2"

         dest: "/etc/nginx/sites-enabled/{{ item }}.conf"

      with_items: "{{ siteslist }}"

      become: yes

      notify: nginxrestart
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"


- name: For CentOS
  block: ----CentOS----
    - name: Install EPEL
      yum:
        pkg: epel-release
      beckome: yes

    - name: Install nginx to CentOS

      apt:

         pkg: nginx

      become: yes

    - name: Create dir for websites

      file:

         path: /var/www/{{ item }}

         state: directory

      become: yes

      with_items: "{{ siteslist }}"

    - name: Create nginx config files

      template:

         src: "testsite.j2"

         dest: "/etc/nginx/sites-enabled/{{ item }}.conf"

      with_items: "{{ siteslist }}"

      become: yes

      notify: nginxrestart
  when: ansible_os_family == "CentOS" or ansible_os_family == "RedHat"

