---

  - name: Install nginx

    apt:

       pkg: nginx

    become: yes

  - name: Create dir for websites

    file:

       path: /var/www/{{ item }}

       state: directory

    become: yes

    with_items: "{{ siteslist }}"

  - name: Create nginx config files

    template:

       src: "testsite.j2"

       dest: "/etc/nginx/sites-enabled/{{ item }}.conf"

    with_items: "{{ siteslist }}"

    become: yes

    notify: nginxrestart
